apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
spec:
  containers:
  - name: webapp
    image: spuny/k8s4devs:webapp
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 3
      failureThreshold: 3
  imagePullSecrets:
    - name:  k8s4devs
